name: portfolio_web
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.1
environment:
  sdk: ^3.8.0-91.0.dev

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^16.0.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  package_info_plus: ^8.3.0
  device_frame: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/phone_frame.png
    - assets/laptop_frame.png
    - assets/lab_bg.jpg
    - assets/stable_lab_bg.jpg 