name: portfolio_web
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.1
environment:
  sdk: ^3.8.0-91.0.dev

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  go_router: ^16.0.0
  package_info_plus: ^8.3.0
  flutter_riverpod: ^2.6.1
  hooks_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/bgs/
    - assets/blueprints/
    - assets/device_frames/
    - assets/demos/
    - assets/demos/b4s/
    - assets/Camilo Santacruz Abadiano resume.pdf